# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch: # 添加手动触发器

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64 libgl1-mesa-dev xorg-dev
          
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: List before build
      run: |
          ls
    
    - name: Build
      run: CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -ldflags "-H windowsgui" -o LdapTest_windows_amd64_${{ steps.date.outputs.date }}.exe

    - name: List after build
      run: |
        ls
    
    - name: Release
      uses: softprops/action-gh-release@v2
      
      with:
          tag_name: ${{ steps.date.outputs.date }}
          token: ${{ secrets.WRITE_TOKEN }}
          files: |
            *.exe
    